### ISSUE TITLE
Overwrite previous character in Japanese IME

### ISSUE THREAD

**Issue by tac0x2a** [tuttieee/vscode-emacs-mcx#115]
Hello.

In writing multi-byte character text by Japanese IME (Google IME), some time overwrote previous character.

![sample](https://user-images.githubusercontent.com/245998/57793818-34aed080-777d-11e9-9ce8-337ce1d4b98c.gif)

This likely to happen in poor cpu machine.
This example is captured in SurfaceGo(Pentium Gold 4415Y).
But, This is hard to occur in Thinkpad X1 Extreme(Core i7-8850H).

When disable Awsome Emacs Keymap extension, this issue become not occurd.

Thanks.

**Comment by tuttieee** [comment]
Thank you for reporting the issue. I will tackle this.

-------
### memo

Related info:

* https://github.com/VSCodeVim/Vim/issues/341
  * PR: https://github.com/VSCodeVim/Vim/pull/446
* https://github.com/VSCodeVim/Vim/issues/1287
  * PR: https://github.com/VSCodeVim/Vim/pull/3214

**Comment by tuttieee** [comment]
## Background

### Type/Composition events with Japanese IME
In case the user types "あい" then press Enter:

1. When user types "あ"
    1. "compositionStart" event is invoked
    2. "type" event is invoked with `{"text": "あ"}`
2. When user types "い"
    1. "replacePreviousChar" event is invoked with `{"text": "あい", "replaceCharCnt" :1}`
3. When user types Enter
    1. "compositionEnd" event is invoked.

### This plugin's event binding
* This plugin binds its original event handler to `type` event.
  * This is for #78 
  * In the event handler, after prefix arguments are processed, the process is delegated to the normal `default:type` command.

## Hypothesis
* If processing prefix arguments takes too much time in `type` event handler somehow, `replacePreviousChar` can be invoked **before** `default:type` command.
* This can make the previous character deleted.

## Possible solution
* To ensure that **ALL** `replacePreviousChar` events between `compositionStart` and `compositionEnd` are invoked AFTER `default:type`.

**Comment by tuttieee** [comment]
Memo

### Env
```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

Set the log level to debug

### Action
1. Create new tab (command+n)
2. Type `* ` w/o IME
3. Switch the IME on.
4. Input `AL` with IME (type shift-a, shift-l)
5. The resultant text was `*AAL`, whereas it should be `* AL`.

### Log at the bug case:
(The resultant text was `*AAL`)
```

console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = "*"
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: "*", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: "*")
console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = " "
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: " ", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: " ")
console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = "A"
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: "A", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: "A")
```

(This log was complete. There was no type command for "L")

--------

### Log at the successful case:
The resultant text was `* AL`.

```
console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = "*"
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: "*", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: "*")
console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = " "
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: " ", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: " ")
console.ts:137 [Extension Host] debug: [command]	 Command executed: "type"
console.ts:137 [Extension Host] debug: [type command]	 args.text = "A"
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.handleType]	 Not in prefix argument mode. exit.
console.ts:137 [Extension Host] debug: [PrefixArgumentHandler.cancel]
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Single char (text: "A", prefix argument: undefined).
console.ts:137 [Extension Host] debug: [EmacsEmulator.type]	 Execute "default:type" (text: "A")
```

### Next action
Set logger to `compositionStart` and `compositionEnd` events.

**Comment by tuttieee** [comment]
こちらのissueの解決の候補となる実装を書きました。
しかし、このバグは毎回再現するわけでなく、確信を持って確認するのが難しい状況です。
さらにVSCodeの文字入力機能に関する低レベルなコマンドをフックする修正となっており、文字入力全般に関する安定性も心配です。
そこで、まずはVS Marketにはリリースせず、.vsixファイル（extensionをバンドルしたファイル）をGitHubのリリースページで配布することにしました。
この.vsixファイルで本拡張をインストールし、**検証に協力していただけないでしょうか？**
↓こちらから.vsixファイルをDLしてインストールしてください（Command paletteの"Extensions: Install from VSIX..."からできます）
https://github.com/tuttieee/vscode-emacs-mcx/releases/tag/v0.20.0-dev.0
しばらく（１週間程度？）使ってみて問題がなさそうなら報告していただけると助かります。
私自身も使っています。
安定していそうならmasterに取り込んでMarketにリリースします。

注: macOSでことえりのライブ変換と併用すると、長めの文字列を入力した際に変換結果が二重に表示されるバグに遭遇するかもしれません。
こちらはVSCode本体のrepositoryにissueを投げてあります: https://github.com/microsoft/vscode/issues/98328
最終的にリリースする際には、本修正を有効にするか無効にするかをConfigで選べるようにする予定です（どちらも一長一短で完全な解決ではないですが、ワークアラウンドとして）

I made a new implementation that can be a candidate of a fix to this issue, but it's not very confirmed because it's difficult to reproduce the bug frequently and check the fix.
In addition, low-level VSCode commands related to character input has been modified and I worry about the stability.
Then, I published the .vsix file (the bundle file of the extension) on GitHub release page, instead of releasing it in the VS Market.
So, **can you please join checking the fix using the .vsix file?**
You can download the file from the link below and install it via "Extensions: Install from VSIX..." in the Command Palette.
https://github.com/tuttieee/vscode-emacs-mcx/releases/tag/v0.20.0-dev.0
I'm also using it now of course.
If it looks stable when you used it for about a week, please report it.
I will merge it into the master branch and release it to the Market if it looks good.

NOTE: If you are using the Japanese IME of macOS with Live Conversion, you find a bug where the converted input looks double.
I created an issue on the VSCode repository: https://github.com/microsoft/vscode/issues/98328
I'm planning to make it possible to turn off the fix here in the public release. It's not a complete solution, but a workaround though.

**Comment by tuttieee** [comment]
↓こちらの.vsixファイルから本拡張をインストールして、本issueが解決されているかチェックしてみてください。
↓Please check if this issue is resolved by installing a new version of this extension from the link below:
https://github.com/tuttieee/vscode-emacs-mcx/releases/download/v0.20.0-dev.0/emacs-mcx-0.20.0-dev.0.vsix

---

こちらのissueの解決の候補となる実装を書きました。
しかし、このバグは毎回再現するわけでなく、確信を持って確認するのが難しい状況です。
さらにVSCodeの文字入力機能に関する低レベルなコマンドをフックする修正となっており、文字入力全般に関する安定性も心配です。
そこで、まずはVS Marketにはリリースせず、.vsixファイル（extensionをバンドルしたファイル）をGitHubのリリースページで配布することにしました。
この.vsixファイルで本拡張をインストールし、**検証に協力していただけないでしょうか？**
↓こちらから.vsixファイルをDLしてインストールしてください（Command paletteの"Extensions: Install from VSIX..."からできます）
https://github.com/tuttieee/vscode-emacs-mcx/releases/tag/v0.20.0-dev.0
しばらく（１週間程度？）使ってみて問題がなさそうなら報告していただけると助かります。
私自身も使っています。
安定していそうならmasterに取り込んでMarketにリリースします。

注: macOSでことえりのライブ変換と併用すると、長めの文字列を入力した際に変換結果が二重に表示されるバグに遭遇するかもしれません。
こちらはVSCode本体のrepositoryにissueを投げてあります: https://github.com/microsoft/vscode/issues/98328
最終的にリリースする際には、本修正を有効にするか無効にするかをConfigで選べるようにする予定です（どちらも一長一短で完全な解決ではないですが、ワークアラウンドとして）

I made a new implementation that can be a candidate of a fix to this issue, but it's not very confirmed because it's difficult to reproduce the bug frequently and check the fix.
In addition, low-level VSCode commands related to character input has been modified and I worry about the stability.
Then, I published the .vsix file (the bundle file of the extension) on GitHub release page, instead of releasing it in the VS Market.
So, **can you please join checking the fix using the .vsix file?**
You can download the file from the link below and install it via "Extensions: Install from VSIX..." in the Command Palette.
https://github.com/tuttieee/vscode-emacs-mcx/releases/tag/v0.20.0-dev.0
I'm also using it now of course.
If it looks stable when you used it for about a week, please report it.
I will merge it into the master branch and release it to the Market if it looks good.

NOTE: If you are using the Japanese IME of macOS with Live Conversion, you can find a bug where the converted input looks double.
I created an issue on the VSCode repository: https://github.com/microsoft/vscode/issues/98328
I'm planning to make it possible to turn off the fix here to avoid it in the public release. It will not be a complete solution, but a workaround though.

**Comment by suchi** [comment]
残念ながらまだ解決しないようです。確実な再現パターンとしては jsファイルで
```
foo() ; // valueがうまく入力できない
```
これを入力時に "value/が/うまく/入力/できない" のスラッシュで変換確定すると
"vvaluがうまく入入できない" となります。コメントキャラクタの後ろでのみ再現します。

**Comment by tuttieee** [comment]
@suchi レポートありがとうございます。以下の情報もいただけるでしょうか？

* VSCode version
* OS
* IME

**Comment by suchi** [comment]
失礼、基本情報が抜けていました

- VSCode 1.45.0
- OS: Windows 10 Pro (10.0.18363)
- IME: ATOK 2015(28.0.7) (ATOK 2017の環境での再現も確認しています)

**Comment by tuttieee** [comment]
上記の開発版では問題は解決していませんでした（さらに悪いことにSKKとの相性は悪化しました）。別の解決を試みたので、こちらのバージョンを以下のリンク先の.vsixファイルからをインストールして、本issueが解決されているかチェックしてみてください。
↓The previous development version did not resolve the problem (and it worked worse with SKK). I tried another solution and please check if this issue is resolved by installing the new version of this extension from the link below:
https://github.com/tuttieee/vscode-emacs-mcx/releases/download/v0.20.0-dev.1/emacs-mcx-0.20.0-dev.1.vsix

---

@suchi 前バージョンに関してご協力ありがとうございました。こちらのバージョンも試していただけると幸いです。

**Comment by tuttieee** [comment]
すみません、上記バージョンは不完全でした。↓こちらでお願いします。
Sorry, in the previous release the fix was not fully applied. Please try this version.
https://github.com/tuttieee/vscode-emacs-mcx/releases/download/v0.20.0-dev.2/emacs-mcx-0.20.0-dev.2.vsix

**Comment by tuttieee** [comment]
It may be a bug derived from VSCode itself. I created an issue in the VSCode repository that is linked above.

**Comment by suchi** [comment]
```
foo(); // vvaluがうまく入入できない 0.20.0-dev.0
foo(); // valueがうまく入力できない 0.20.0-dev.2
```
申し訳ありません、dev.1のメンション見落としていました。今試したところ、dev.2では正常に入力できました!

- VSCode version: 1.46.1 
- OS: Windows 10 Pro (10.0.18363)
- IME: ATOK 2015(28.0.7)

**Comment by tuttieee** [comment]
@suchi どうもありがとうございます 🙇 
dev.2の変更はすでにMarketに0.20.xとして出ておりますので、そちらを使い続けていただければと思います（もし本件の解決にはならなくても、他にも意味のある変更だったので、本Issueの状況とは独立にリリースしてしまいました）。

一方で、最近私の環境で、dev.2でも似たような現象が再現してしまいました。
この現象を起こす要因が複数ありうる気がしており、そのうち一つがdev.2で潰したもの、また別の一つが https://github.com/microsoft/vscode/issues/102291 かと思っています。
こちらも回避するワークアラウンドを考えています。

なんにせよ、まずはそちらの環境で解決したとのこと、よかったです。ご報告どうもありがとうございました。

**Comment by AquiTCD** [comment]
AquaSKKと使用中ですが1週間ほど使用して特に問題なく動いてる様子です。
大変たすかります、ありがとうございます。ご報告まで。

VSCode version: 1.47.0
OS: macOS 10.14.6
IME: AquaSKK 4.7.0

**Comment by tuttieee** [comment]
@AquiTCD どうもありがとうございます。よかったです。
