### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by LucioFranco** [tuttieee/vscode-emacs-mcx#136]
Just getting started with this library and I ran into a few `nextLine` command not found. Any idea why this might be happening? I had it working earlier but all of a sudden everything stopped working.

**Comment by mbforbes** [comment]
I'm also having these issues. Previously, I would run into this problem when there was a VS Code update available, and updating would fix it. But today, none of the keybindings work for me! I see this why I try to use the commands:

![Screen Shot 2019-08-29 at 1 55 26 PM](https://user-images.githubusercontent.com/1170062/63975998-2acb8780-ca65-11e9-9c35-b423273b0ec0.png)

Any help would be greatly appreciated! This is my favorite VS Code Emacs plugin! :-)

**Comment by LucioFranco** [comment]
@mbforbes so I was able to get it to work by completely reinstall vscode. Not the best solution but it works.

**Comment by mbforbes** [comment]
(may be related to #111, and also may be related to the SSH Remote extension—could be causing problems for other extensions!)

(@LucioFranco thanks for the info!)

**Comment by mbforbes** [comment]
So sorry for all the spam. I was struggling with this for about an hour and the emacs keybindings were the symptom, not the cause. I think this was due to bugs in SSH Remote extension, which crashed the extension service, killing extensions including this one! I finally restarted my remote machine, which has (at least for now) fixed the issue. Thank you again, and sorry about the spam!

**Comment by tuttieee** [comment]
Thank you all!
