### ISSUE TITLE
Please support M-l, M-u

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#23]
Please support M-l, M-u:

https://www.gnu.org/software/emacs/manual/html_node/emacs/Case.html

- M-l
    - Convert following word to lower case (downcase-word). 
- M-u
    - Convert following word to upper case (upcase-word).

**Comment by ganaware** [comment]
Assigning M-l and M-l to editor.action.transformToLowercase and editor.action.transformToUppercase is good work.

But I think, what is important for M-u and M-l is that they move cursor in additon to upcase (or downcase) word.  For example, I can upcase all words of "awesome emacs keymap" only by typing M-u M-u M-u.

If M-u and M-l executed the following command sequences, they would be more resemble to the original Emacs, I think.

1. emacs-mcx.cursorWordRight
2. editor.action.transformTo(Lower|Upper)case

**Comment by tuttieee** [comment]
Hi, v0.2.0 has been released which includes this functionality.

As explained in #53, the current implementation has a drawback which I think though can be ignored in almost all practical cases.
Then I remain this issue opened and will fix it, but the priority not so high since I think the drawback is not a big problem.

**Comment by ganaware** [comment]
This feature works very good in most cases.
Thank you.
