### ISSUE TITLE
mac os: ctrl-a & ctrl-e & ctrl-b & ctrl-f not work in find widget

### ISSUE THREAD

**Issue by ColorFuzzy** [tuttieee/vscode-emacs-mcx#271]
`mac os: ctrl-a & ctrl-e & ctrl-b & ctrl-f not work in find widget`, it works well some days ago, but it doesn't work after upgrade to the new extension version.

**Comment by tuttieee** [comment]
mm, I can't reproduce it in my mac env.
One possible cause of this problem is the modified keybinding definitions introduced in 0.19.4 (though it was intended to be an internal change with no effect), while I cannot find any changes between the behaviors of 0.19.4 and older versions in the find widget.

> it works well some days ago, but it doesn't work after upgrade to the new extension version.

Let me confirm that "it works" here means that these keybindings in the find widget close the widget and move the cursors in the main editor. (or any other expected behaviors?)

Additionally, can you try using previous versions of the extension to check if the problem occurs.
You can install older versions by the following steps:
1. Open the palette and select "Extensions: Show Installed Extensions"
2. In the list, find "Awesome Emacs Keymap" and click the gear icon to open the menu.
3. Select "Install Another Version..."
4. Select the version to install.

**Comment by ColorFuzzy** [comment]
![image](https://user-images.githubusercontent.com/1814478/80556473-3dd49400-8a06-11ea-92d0-de22b759df3e.png)

1. In version `0.8.0`, `ctrl+a/e/f/b` will move the cursor in the search box
2. In version `0.9.0 and above`, `ctrl+a/e/f/b` will just quit the search process and hide the search box
3. Test these two versions with the same vscode version & settings.

**vscode info:**

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by tuttieee** [comment]
I see. That's intended behavior introduced in the specified version.
Please see the discussion in #137 and follow it.
