### ISSUE TITLE
Do not clear selections when C-M-b, C-M-f

### ISSUE THREAD

**Issue by ganaware** [tuttieee/vscode-emacs-mcx#58]
The original emacs doesn’t clear a mark when moving the cursor.

But in 0.4.0 of the Awesome Emacs Keymap, C-M-b (sexp.moveBackward) and C-M-f (sexp.moveForward) clear selections.

Don't clear selections, please.

**Comment by cpryland** [comment]
Don't you have to clear the selection by definition, if you're moving the cursor?

**Comment by tuttieee** [comment]
Currently, [haruhi-s.sexp](https://github.com/haruhi-s/sexp) extension is used for sexp functions (https://github.com/tuttieee/vscode-emacs-mcx/blob/ebc5c8b99559394fea51f953c6e3df9d6ae3fa75/package.json#L32).
But Awesome Emacs Kepmap's mark-mode management is not integrated to it.

Then, I will stop using that external extension and implement the original sexp behavior in this extension working with mark-mode.

**Comment by tuttieee** [comment]
Memo:
Use https://robert.kra.hn/past-projects/paredit-js.html

**Comment by tuttieee** [comment]
@ganaware Hi, new version 0.6.0 released and this problem is fixed in that version.
I stopped utilizing the external extension `haruhi-s.sexp` and implement sexp functionalities embedded in this extension. Then, in version 0.6.0, `slurp` and `barf` were eliminated.
Implementing these functionalities is technically possible and please tell me if it is needed.
If not, I will do it after other things.

**Comment by ganaware** [comment]
The version 0.6.0 works as expepected.
Thank you!

<code>sexp.slurp</code> and <code>sexp.barf</code> of haruhi-s.sexp correspond to <code>mark-sexp</code> (<kbd>C-M-SPC</kbd>) of Emacs, but I have never use it. So, I don't need them.

**Comment by tuttieee** [comment]
Thanks!
I'm closing this issue and the rest of related tasks will be in #65
